# Day 2 – NumPy Indexing & Slicing

## Objective
Learn how to access and modify elements in NumPy arrays.

**Name:** Ponmalar

**Day:** 2

In [1]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])
print(numbers[2])
print(numbers[-1])
print(numbers[-2])


10
30
50
40


In [2]:
# Slicing

print(numbers[1:4])
print(numbers[:3])
print(numbers[2:])
print(numbers[::-1])

[20 30 40]
[10 20 30]
[30 40 50]
[50 40 30 20 10]


In [3]:
numbers[0] = 100
numbers[2] = 300

print(numbers)

[100  20 300  40  50]


In [4]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matrix)

print("First row:", matrix[0])
print("Second row:", matrix[1])

print("First element:", matrix[0,0])
print("Center element:", matrix[1,1])
print("Last element:", matrix[2,2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
First row: [10 20 30]
Second row: [40 50 60]
First element: 10
Center element: 50
Last element: 90


In [5]:
print(matrix[:, 0])

print(matrix[1, :])

print(matrix[0:2, 1:3])

print(matrix[:, 1:])

[10 40 70]
[40 50 60]
[[20 30]
 [50 60]]
[[20 30]
 [50 60]
 [80 90]]


In [6]:
matrix[0,0] = 100
matrix[2,1] = 800

print(matrix)

[[100  20  30]
 [ 40  50  60]
 [ 70 800  90]]


In [7]:
import numpy as np

marks = np.array([75, 92, 81, 95, 67, 88])

print("Original Marks:")
print(marks)

print("\nMarks greater than 85:")
print(marks[marks > 85])

Original Marks:
[75 92 81 95 67 88]

Marks greater than 85:
[92 95 88]


In [8]:
numbers = np.array([10,20,30,40,50,60])

print(numbers[[0,2,5]])

[10 30 60]
