# Day 3 – NumPy Operations & Broadcasting

## Objective
Learn mathematical operations on NumPy arrays.

**Name:** Ponmalar

**Day:** 3

In [1]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print("Array A:", a)
print("Array B:", b)

Array A: [10 20 30 40]
Array B: [1 2 3 4]


In [2]:
print(a+b)

[11 22 33 44]


In [3]:
print(a-b)

[ 9 18 27 36]


In [4]:
print(a*b)

[ 10  40  90 160]


In [5]:
print(a/b)


[10. 10. 10. 10.]


In [6]:
print(a**2)

[ 100  400  900 1600]


In [7]:
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558 6.32455532]


In [8]:
a * b

array([ 10,  40,  90, 160])

In [9]:
a.dot(b)

np.int64(300)

In [10]:
import numpy as np

marks = np.array([80, 90, 70, 60])

print("Original Marks:")
print(marks)

print("\nAfter adding 5 grace marks:")
print(marks + 5)

Original Marks:
[80 90 70 60]

After adding 5 grace marks:
[85 95 75 65]


In [11]:
print(marks * 2)

[160 180 140 120]


In [12]:
a = np.array([10,20,30])

b = np.array([1])

print(a + b)

[11 21 31]


In [13]:
prices = np.array([100,200,300,400])

gst = 18

final_price = prices + gst

print(final_price)

[118 218 318 418]
