# Day 4 – NumPy Universal Functions

## Objective
Learn statistical and mathematical functions in NumPy.

**Name:** Ponmalar

**Day:** 4

In [1]:
import numpy as np

marks = np.array([78, 92, 65, 88, 95, 70, 88])

print("Marks:")
print(marks)

Marks:
[78 92 65 88 95 70 88]


In [2]:
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

Maximum: 95
Minimum: 65


In [3]:
print("Sum:", np.sum(marks))
print("Average:", np.mean(marks))

Sum: 576
Average: 82.28571428571429


In [4]:
print("Median:", np.median(marks))

Median: 88.0


In [5]:
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))

Standard Deviation: 10.619581451454744
Variance: 112.77551020408164


In [6]:
print("Index of Maximum:", np.argmax(marks))
print("Index of Minimum:", np.argmin(marks))

Index of Maximum: 4
Index of Minimum: 2


In [7]:
print(np.sort(marks))

[65 70 78 88 88 92 95]


In [8]:
print(np.unique(marks))

[65 70 78 88 92 95]


In [9]:
print(np.where(marks > 80))

(array([1, 3, 4, 6]),)


In [10]:
print(np.clip(marks,70,90))

[78 90 70 88 90 70 88]


In [11]:
sales = np.array([25000,32000,28000,35000,30000])

print("Sales:", sales)
print("Highest Sales:", np.max(sales))
print("Lowest Sales:", np.min(sales))
print("Average Sales:", np.mean(sales))
print("Total Sales:", np.sum(sales))

Sales: [25000 32000 28000 35000 30000]
Highest Sales: 35000
Lowest Sales: 25000
Average Sales: 30000.0
Total Sales: 150000


# 📊 Mini Project – Student Marks Analysis

## 🎯 Objective
Analyze a dataset of student marks using NumPy and generate useful insights using statistical functions, indexing, broadcasting, and filtering.

### Concepts Used
- NumPy Arrays
- Indexing and Slicing
- Broadcasting
- Maximum and Minimum
- Mean and Median
- Sum
- Sorting
- Unique Values
- Argmax
- Boolean Indexing
- np.clip()

### Problem Statement
A teacher wants to analyze the marks of students in a class. The goal is to identify the highest and lowest marks, calculate the average, find top-performing students, identify students who need additional support, and generate a final report after awarding grace marks.

### Expected Outcome
By the end of this project, you will be able to:
- Analyze student marks using NumPy.
- Perform statistical calculations.
- Filter data based on conditions.
- Apply broadcasting to update marks.
- Generate a simple performance report.

In [12]:
import numpy as np

marks = np.array([78, 92, 65, 88, 95, 70, 88, 81, 76, 90])

print("Student Marks")
print(marks)

Student Marks
[78 92 65 88 95 70 88 81 76 90]


## 📈 Task 1: Basic Statistical Analysis

Calculate the highest mark, lowest mark, total marks, average mark, and median of the dataset.

In [13]:
print("Highest Mark:", np.max(marks))
print("Lowest Mark:", np.min(marks))
print("Total Marks:", np.sum(marks))
print("Average Mark:", np.mean(marks))
print("Median Mark:", np.median(marks))

Highest Mark: 95
Lowest Mark: 65
Total Marks: 823
Average Mark: 82.3
Median Mark: 84.5


## 🏆 Task 2: Identify High Performing Students

Find all students who scored more than 85 marks.

In [14]:
print("Students scoring above 85:")
print(marks[marks > 85])

Students scoring above 85:
[92 88 95 88 90]


## 📚 Task 3: Identify Students Needing Improvement

Find students who scored below 70 marks.


In [16]:
print("Students scoring below 70:")
print(marks[marks < 70])

Students scoring below 70:
[65]


## 📊 Task 4: Sort and Remove Duplicate Marks

Sort the marks in ascending order and display only unique marks.

In [17]:
print("Sorted Marks:")
print(np.sort(marks))

print("Unique Marks:")
print(np.unique(marks))

Sorted Marks:
[65 70 76 78 81 88 88 90 92 95]
Unique Marks:
[65 70 76 78 81 88 90 92 95]


## 🥇 Task 5: Find the Top Scorer

Identify the position (index) of the student with the highest mark.

In [18]:
highest_index = np.argmax(marks)

print("Top Scorer Index:", highest_index)
print("Top Score:", marks[highest_index])

Top Scorer Index: 4
Top Score: 95


## ➕ Task 6: Award Grace Marks

Add 5 grace marks to every student using NumPy broadcasting.

In [19]:
updated_marks = marks + 5

print(updated_marks)

[ 83  97  70  93 100  75  93  86  81  95]


## 🎯 Task 7: Limit Maximum Marks

Ensure that no student's marks exceed 100 using the `np.clip()` function.

In [20]:
final_marks = np.clip(updated_marks, 0, 100)

print(final_marks)

[ 83  97  70  93 100  75  93  86  81  95]


## 📋 Final Performance Report

Generate a summary report after applying grace marks.

In [21]:
print("===== FINAL REPORT =====")
print("Highest Mark :", np.max(final_marks))
print("Lowest Mark  :", np.min(final_marks))
print("Average Mark :", np.mean(final_marks))
print("Students Scoring Above 90 :", final_marks[final_marks >= 90])

===== FINAL REPORT =====
Highest Mark : 100
Lowest Mark  : 70
Average Mark : 87.3
Students Scoring Above 90 : [ 97  93 100  93  95]


# ✅ Conclusion

In this mini project, student marks were analyzed using NumPy. Statistical measures such as maximum, minimum, mean, median, and total were calculated. High-performing students and students needing improvement were identified. Broadcasting was used to award grace marks, and `np.clip()` ensured that marks remained within the valid range. This project demonstrates how NumPy can efficiently analyze and manipulate numerical datasets.