# Day 4 – NumPy Universal Functions

## Objective
Learn statistical and mathematical functions in NumPy.

**Name:** Ponmalar

**Day:** 4

In [1]:
import numpy as np

marks = np.array([78, 92, 65, 88, 95, 70, 88])

print("Marks:")
print(marks)

Marks:
[78 92 65 88 95 70 88]


In [2]:
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

Maximum: 95
Minimum: 65


In [3]:
print("Sum:", np.sum(marks))
print("Average:", np.mean(marks))

Sum: 576
Average: 82.28571428571429


In [4]:
print("Median:", np.median(marks))

Median: 88.0


In [5]:
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))

Standard Deviation: 10.619581451454744
Variance: 112.77551020408164


In [6]:
print("Index of Maximum:", np.argmax(marks))
print("Index of Minimum:", np.argmin(marks))

Index of Maximum: 4
Index of Minimum: 2


In [7]:
print(np.sort(marks))

[65 70 78 88 88 92 95]


In [8]:
print(np.unique(marks))

[65 70 78 88 92 95]


In [9]:
print(np.where(marks > 80))

(array([1, 3, 4, 6]),)


In [10]:
print(np.clip(marks,70,90))

[78 90 70 88 90 70 88]


In [11]:
sales = np.array([25000,32000,28000,35000,30000])

print("Sales:", sales)
print("Highest Sales:", np.max(sales))
print("Lowest Sales:", np.min(sales))
print("Average Sales:", np.mean(sales))
print("Total Sales:", np.sum(sales))

Sales: [25000 32000 28000 35000 30000]
Highest Sales: 35000
Lowest Sales: 25000
Average Sales: 30000.0
Total Sales: 150000
