# Day 5 – NumPy Array Manipulation

## Objective
Learn how to reshape, combine, split, and manipulate NumPy arrays.

**Name:** Ponmalar

**Day:** 5

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
matrix = arr.reshape(3,4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
print(matrix.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
print(matrix.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
print(matrix.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [6]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [7]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [8]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [9]:
numbers = np.array([10,20,30,40,50,60])

parts = np.split(numbers,3)

print(parts)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [10]:
arr = np.array([1,2,3,4,5,6])

print(np.resize(arr,10))

[1 2 3 4 5 6 1 2 3 4]


In [11]:
arr = np.array([10,20,30])

new_arr = np.append(arr,40)

print(new_arr)

[10 20 30 40]


In [12]:
arr = np.array([10,20,40])

new_arr = np.insert(arr,2,30)

print(new_arr)

[10 20 30 40]


In [13]:
arr = np.array([10,20,30,40])

new_arr = np.delete(arr,1)

print(new_arr)

[10 30 40]


# 📊 Mini Project – Employee Salary Analysis

## Objective
Analyze employee salary data using NumPy array manipulation techniques.

### Concepts Used
- Reshape
- Flatten
- Transpose
- Concatenate
- Stack
- Split
- Append
- Insert
- Delete
- Resize

### Problem Statement
A company wants to organize employee salary data for analysis. The HR department needs to reshape salary records, add new employees, remove resigned employees, and prepare the dataset for reporting.

In [14]:
import numpy as np

salary = np.array([25000,30000,35000,40000,45000,50000])

print("Employee Salaries")
print(salary)

Employee Salaries
[25000 30000 35000 40000 45000 50000]


In [15]:
salary_matrix = salary.reshape(2,3)

print(salary_matrix)

[[25000 30000 35000]
 [40000 45000 50000]]


In [16]:
print("Transpose")

print(salary_matrix.T)

Transpose
[[25000 40000]
 [30000 45000]
 [35000 50000]]


In [17]:
print("Flatten")

print(salary_matrix.flatten())

Flatten
[25000 30000 35000 40000 45000 50000]


In [18]:
new_salary = np.append(salary,55000)

print(new_salary)

[25000 30000 35000 40000 45000 50000 55000]


In [19]:
updated_salary = np.insert(new_salary,2,32000)

print(updated_salary)

[25000 30000 32000 35000 40000 45000 50000 55000]


In [20]:
final_salary = np.delete(updated_salary,1)

print(final_salary)

[25000 32000 35000 40000 45000 50000 55000]


In [21]:
dept1 = np.array([25000,30000])

dept2 = np.array([35000,40000])

print(np.concatenate((dept1,dept2)))

[25000 30000 35000 40000]


In [22]:
print(np.vstack((dept1,dept2)))

[[25000 30000]
 [35000 40000]]


In [23]:
print(np.hstack((dept1,dept2)))

[25000 30000 35000 40000]


In [25]:
print(np.resize(final_salary,10))

[25000 32000 35000 40000 45000 50000 55000 25000 32000 35000]


In [26]:
parts = np.array_split(final_salary,2)

print(parts)

[array([25000, 32000, 35000, 40000]), array([45000, 50000, 55000])]


# ✅ Conclusion

In this project, employee salary data was manipulated using NumPy. The dataset was reshaped, flattened, transposed, expanded by adding new employees, updated using insertion and deletion, combined using stacking techniques, and resized for reporting. These operations demonstrate common preprocessing tasks performed before analyzing real-world datasets.