# Day 6 – Boolean Masking and Filtering

## Objective
Learn how to filter data, apply conditions, replace values, and handle missing values using NumPy.

**Name:** Ponmalar

**Day:** 6


In [1]:
import numpy as np
marks = np.array([45, 67, 89, 34, 92, 76, 58, 99, 81, 39])

print(marks)

[45 67 89 34 92 76 58 99 81 39]


In [2]:
print(marks > 70)

[False False  True False  True  True False  True  True False]


In [3]:
print(marks[marks > 70])

[89 92 76 99 81]


In [4]:
print(marks[marks < 50])

[45 34 39]


In [5]:
print(marks[(marks > 60) & (marks < 90)])

[67 89 76 81]


In [6]:
print(marks[(marks < 40) | (marks > 90)])

[34 92 99 39]


In [7]:
marks[marks < 40] = 40

print(marks)

[45 67 89 40 92 76 58 99 81 40]


In [8]:
data = np.array([10,20,np.nan,40,50,np.nan])

print(data)

[10. 20. nan 40. 50. nan]


In [9]:
print(np.isnan(data))

[False False  True False False  True]


In [10]:
data[np.isnan(data)] = 0

print(data)

[10. 20.  0. 40. 50.  0.]


# 📊 Mini Project – Employee Performance Analysis

## Objective
Analyze employee performance scores using NumPy. Filter employees based on performance, identify top performers, update low scores, and handle missing values.

### Concepts Used
- NumPy Arrays
- Boolean Masking
- Filtering
- Multiple Conditions
- Missing Values (NaN)
- Statistical Functions

### Problem Statement
A company wants to analyze employee performance scores. HR needs to identify high-performing employees, employees needing training, calculate average performance, and replace missing scores before generating a report.

In [11]:
import numpy as np
scores = np.array([78, 92, 55, 81, 45, 99, 67, 88, 39, 74])

print("Employee Scores")
print(scores)

Employee Scores
[78 92 55 81 45 99 67 88 39 74]


In [12]:
print("Highest Score:", np.max(scores))
print("Lowest Score:", np.min(scores))
print("Average Score:", np.mean(scores))
print("Total Score:", np.sum(scores))

Highest Score: 99
Lowest Score: 39
Average Score: 71.8
Total Score: 718


In [13]:
print("Employees scoring above 80")
print(scores[scores > 80])

Employees scoring above 80
[92 81 99 88]


In [14]:
print("Employees scoring below 50")
print(scores[scores < 50])

Employees scoring below 50
[45 39]


In [15]:
print(scores[(scores >= 60) & (scores <= 90)])

[78 81 67 88 74]


In [16]:
scores[scores < 50] = 50

print(scores)

[78 92 55 81 50 99 67 88 50 74]


In [17]:
attendance = np.array([98, np.nan, 87, 91, np.nan, 95])

print(attendance)

[98. nan 87. 91. nan 95.]


In [18]:
print(np.isnan(attendance))

[False  True False False  True False]


In [19]:
attendance[np.isnan(attendance)] = 0

print(attendance)

[98.  0. 87. 91.  0. 95.]


## 📋 Final Performance Report

In [20]:
print("===== PERFORMANCE REPORT =====")

print("Highest Score :", np.max(scores))
print("Lowest Score :", np.min(scores))
print("Average Score :", np.mean(scores))
print("Employees Above 80 :", scores[scores > 80])
print("Employees Below 60 :", scores[scores < 60])

===== PERFORMANCE REPORT =====
Highest Score : 99
Lowest Score : 50
Average Score : 73.4
Employees Above 80 : [92 81 99 88]
Employees Below 60 : [55 50 50]


# ✅ Conclusion

This project analyzed employee performance data using NumPy. Boolean masking was used to filter employees based on performance, low scores were updated using conditional selection, missing attendance values were handled using `np.isnan()`, and a final report was generated. These are common preprocessing and analysis techniques used in real-world data analytics.